### ISSUE TITLE
Multiplayer Disabled check Microsoft Account Settings

### ISSUE THREAD

**Issue by cool-dev-code** [DIDIRUS4/AstralRinth#4]
### Describe the bug

I just installed Fabric 1.16.5 with offline account and got this "Multiplayer Disabled check Microsoft Account Settings"

### Steps to reproduce

1. Download Minecraft 1.16.5 Fabric
2. Start Minecraft
3. You wont be able to click multiplayer (button gets greyed out)

### Expected behavior

Should start Minecraft.

### System information

Windows 11 Pro
23 H2
Fully uptodate

**Comment by cool-dev-code** [comment]
![image](https://github.com/DIDIRUS4/AstralRinth/assets/65089197/d6648d4f-4d5b-42b6-811b-919788fd009a)

**Comment by cool-dev-code** [comment]
![image](https://github.com/DIDIRUS4/AstralRinth/assets/65089197/36ec973e-b4f7-445c-bbc6-3ecaff97ae03)

**Comment by DIDIRUS4** [comment]
This is a Minecraft feature coded by Microsoft. (Maybe the bug, because it's not reproduced in the latest versions of the game) 

Modrinth downloads game patches from original Microsoft servers, which do not have any third-party code base.

Our fork doesn't patch any Minecraft patches for security reasons. Of course, we can boot up our Astralium Project Web API for downloads of modifications for 1.16.5, but I think it's not needed.

Available fix for today on offline account type:

- Turn off the internet / wireless network
- Run Minecraft 1.16.5 with an offline account type
- Wait before the game's main menu is presented
- Turn on the internet / wireless network.

**Comment by cool-dev-code** [comment]
Thanks i will try it
